# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20170327_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.AddField(
            model_name='order',
            name='food_list',
            field=models.ManyToManyField(to='market.Food'),
        ),
    ]
