# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20170329_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='food',
        ),
        migrations.AddField(
            model_name='comment',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='market.Shop'),
            preserve_default=False,
        ),
    ]
