# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-07 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20170329_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': '美食', 'verbose_name_plural': '美食'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '商家', 'verbose_name_plural': '商家'},
        ),
        migrations.AddField(
            model_name='order',
            name='has_commented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to='img', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(default=0, verbose_name='售价'),
        ),
        migrations.AlterField(
            model_name='food',
            name='sale_num',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(upload_to='img', verbose_name='商标'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.FloatField(default=5.0, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sale_num',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
